### ISSUE TITLE
prominent display of x,y,z max extend, and more

### ISSUE THREAD

**Issue by jcr723** [skyguy126/GCI#13]
Command, Spindle Speed, and Feedrate are given prominent visibility in most recent version.  These values can take on a number of different values in more complex programs.  How do you decided which to display?  I believe the new feature showing this additional information should be modified to more prominently show the maximum extents in x,y,z direction.   If spindle speed and feedrate are shown, we must decide on a way to choose how to display this info when there are more than one value of each in a g-code file.  Again, the space given to the max extents in x,y,z should be made more prominent.  I like the fact that the unit mode is stated (G90) or inch.  We should discuss further.

**Comment by skyguy126** [comment]
@jcr723 The values will change based on the current line when you click play or drag the time slider around.

**Comment by skyguy126** [comment]
Added feature with commit 77ff8f040f32d32206b29e8d1b3bb6eb34d564e6.
