### ISSUE TITLE
Correctly display nc files from HSM Pro

### ISSUE THREAD

**Issue by jcr723** [skyguy126/GCI#14]
Please modify GCI so that it correctly previews this nc file of a simple facing operation.

This file shows the correct preview as created by the Techno previewer
[FaceMillingFace2.docx](https://github.com/skyguy126/GCI/files/607373/FaceMillingFace2.docx)

This is the nc file (github won't accept a simple text file so I put in in Word)
[Face_2.nc.docx](https://github.com/skyguy126/GCI/files/607388/Face_2.nc.docx)

**Comment by skyguy126** [comment]
Fixed with commit 5acfac51a49d6d6f15d03274e4db498290b99eb6.
