### ISSUE TITLE
Correctly display GDF2 preview

### ISSUE THREAD

**Issue by jcr723** [skyguy126/GCI#15]
The attached .nc file for a GDF2 part is correctly previewed in Autodesk HSM but has an error upon loading using GCI ver8.  Please enhance GCI such that it displays preview correctly.  

See attached file
[BlockPeyton_GDF2_nc_File.docx](https://github.com/skyguy126/GCI/files/634401/BlockPeyton_GDF2_nc_File.docx)

**Comment by skyguy126** [comment]
fixed with 07972bf1230227840caabe9d1d2df45e83cb4430
